### ISSUE TITLE
removeFromQueue not removing from queue

### ISSUE THREAD

**Issue by Dalek0967** [danielgindi/node-childprocess-queue#1]
Hi!

I've been using this module for almost a year in a web application so that I can limit the number of running processes so as not to slow down my server with too many programs. It works well, however, I've just recently implemented the ability to cancel processes which are waiting in the queue by calling the `removeFromQueue` method, but even though it returns true for an id I know is in the queue, the process isn't removed and is eventually executed.

Having had a look at the code, I noticed that that method only removes items from the `MAP`, but never touches the `QUEUE` :
```javascript
removeFromQueue: function (id) {

            if (MAP.hasOwnProperty(id)) {
                delete MAP[id];
                return true;
            }

            return false;
}
```

**Comment by danielgindi** [comment]
Thanks for the report :-)
